# Generated by Django 4.2 on 2023-12-14 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_nam2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cpf", models.CharField(blank=True, max_length=255)),
                ("telefone", models.CharField(blank=True, max_length=255)),
                (
                    "foto_perfil",
                    models.ImageField(blank=True, default="static/images/user.png", null=True, upload_to="imagens"),
                ),
                (
                    "usuario",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
