# Generated by Django 4.2 on 2023-12-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="foto_perfil",
            field=models.ImageField(blank=True, default="static/images/user.png", null=True, upload_to="imagens"),
        ),
        migrations.AddField(
            model_name="user",
            name="telefone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Perfil",
        ),
    ]
