# Generated by Django 4.2 on 2023-12-14 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_cpf_user_foto_perfil_user_telefone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="user",
            name="foto_perfil",
        ),
        migrations.RemoveField(
            model_name="user",
            name="telefone",
        ),
    ]
