# Generated by Django 4.2 on 2023-12-15 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_cpf_remove_user_foto_perfil_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("Estado", models.CharField(max_length=100)),
                ("Cidade", models.CharField(max_length=100)),
                ("Pais", models.CharField(max_length=100)),
                ("Data_nascimento", models.DateField(blank=True, null=True)),
                ("profile_picture", models.ImageField(blank=True, null=True, upload_to="profile_pics/")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
