# Generated by Django 4.2 on 2023-11-16 20:26

import core.models
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Postagem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("titulo", models.CharField(max_length=100)),
                ("Data_postagem", models.DateField()),
                ("Texto", models.TextField()),
                ("imagem", models.ImageField(upload_to="imagens")),
                ("Resumo", models.CharField(max_length=255)),
                ("conteudo", models.CharField(max_length=100)),
                ("tipo_arquivo", models.CharField(max_length=50)),
                ("Url", models.CharField(max_length=100)),
                (
                    "categoria_postagem",
                    models.CharField(
                        choices=[
                            ("Matematicos", "Matematicos"),
                            ("Diversidades", "Diversidades"),
                            ("Historia", "Historia"),
                            ("Exercicios", "Exercicios"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
