# Generated by Django 4.2 on 2023-12-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Postagem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensagemContato",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mensagem", models.TextField()),
            ],
        ),
    ]
