# Generated by Django 4.2 on 2023-11-24 18:38

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Postagem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagem",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(core.models.get_sentinel_user),
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="postagem",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(core.models.get_sentinel_user),
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
    ]
