# Generated by Django 4.2 on 2023-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Postagem", "0003_alter_postagem_resumo_alter_postagem_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="Resumo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="postagem",
            name="titulo",
            field=models.CharField(max_length=250),
        ),
    ]
