# Generated by Django 4.2 on 2023-12-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Postagem", "0004_alter_postagem_resumo_alter_postagem_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="Resumo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
