#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --noinput

#npm ci
python manage.py makemigrations core users Postagem
python manage.py migrate



exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/home/app
