# Generated by Django 4.2 on 2023-05-24 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_tabelaexercicios_delete_exercicios"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tabelaexercicios",
            old_name="download",
            new_name="link",
        ),
    ]
