# Generated by Django 4.2 on 2023-05-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_download_tabelaexercicios_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelaexercicios",
            name="link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="tabelaexercicios",
            name="tipo",
            field=models.CharField(max_length=150),
        ),
    ]
