# Generated by Django 4.2 on 2023-05-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_tabelaexercicios_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poesia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=100)),
                ("conteudo", models.TextField()),
            ],
        ),
    ]
