# Generated by Django 4.2 on 2023-05-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_poesia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poesia",
            old_name="conteudo",
            new_name="PrimeiraParte",
        ),
        migrations.AddField(
            model_name="poesia",
            name="SegundaParte",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="poesia",
            name="titulo",
            field=models.CharField(max_length=150),
        ),
    ]
