# Generated by Django 4.2 on 2023-05-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_conteudo_poesia_primeiraparte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poesia",
            name="autor",
            field=models.CharField(default="", max_length=100),
        ),
    ]
