# Generated by Django 4.2 on 2023-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_poesia_autor"),
    ]

    operations = [
        migrations.AddField(
            model_name="poesia",
            name="media_avaliacao",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="poesia",
            name="num_avaliacoes",
            field=models.IntegerField(default=0),
        ),
    ]
