# Generated by Django 4.2 on 2023-05-25 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_poesia_media_avaliacao_poesia_num_avaliacoes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poesia",
            name="media_avaliacao",
        ),
        migrations.RemoveField(
            model_name="poesia",
            name="num_avaliacoes",
        ),
    ]
