# Generated by Django 4.2 on 2023-07-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_poesia_media_avaliacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercicios",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conteudo", models.CharField(max_length=150)),
                ("tipo_arquivo", models.CharField(max_length=30)),
                ("Url", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Matematicos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("imagem", models.ImageField(upload_to="imagens")),
                ("Resumo", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Poesias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("Autor", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Postagem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=150)),
                ("Data_postagem", models.DateField()),
                ("Texto", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("exercicios", "Exercícios"),
                            ("matematicos", "Matemáticos"),
                            ("poesias", "Poesias"),
                            ("historia", "História"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "matematicos",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.matematicos"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Poesia",
        ),
        migrations.DeleteModel(
            name="Tabelaexercicios",
        ),
        migrations.RemoveField(
            model_name="historia",
            name="conteudo",
        ),
        migrations.RemoveField(
            model_name="historia",
            name="titulo",
        ),
    ]
