# Generated by Django 4.2 on 2023-11-09 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_exercicios_matematicos_poesias_postagem_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Exercicios",
        ),
        migrations.DeleteModel(
            name="Historia",
        ),
        migrations.DeleteModel(
            name="Poesias",
        ),
        migrations.RemoveField(
            model_name="postagem",
            name="matematicos",
        ),
        migrations.DeleteModel(
            name="Matematicos",
        ),
        migrations.DeleteModel(
            name="Postagem",
        ),
    ]
